### ISSUE TITLE
The sbt plugin can't be resolved

### ISSUE THREAD

**Issue by liorhar** [scalacenter/scalac-profiling#10]
adding the sbt plugin to my project fails to resolve. is it published yet? do I need to add a customer resolver?
getting this error
![image](https://user-images.githubusercontent.com/821044/31603308-6572fd6c-b268-11e7-86cf-47fc9b1ff02a.png)

**Comment by jvican** [comment]
We will have an official release soon. We've been waiting for 2.12.4 to be released and now we're waiting on the ecosystem to catch up. I'll keep you posted.

**Comment by yanns** [comment]
still a problem for me:
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: ch.epfl.scala#scalac-profiling;1.0.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
```
