### ISSUE TITLE
Color flag seems incorrect in the Usage instructions

### ISSUE THREAD

**Issue by acloudmovingby** [scalacenter/scalac-profiling#116]
The Usage section says to do `--color=scala-compilation` when you run Flamegraph, but that makes it all black and it's hard to distinguish the flamegraph segments:
<img width="1204" alt="image" src="https://github.com/scalacenter/scalac-profiling/assets/30088765/143f5c3a-2aa4-4438-9bca-a5ef4a08338f">

If I remove that flag, we get nicer colors:

<img width="1202" alt="image" src="https://github.com/scalacenter/scalac-profiling/assets/30088765/f5cc16b3-4084-4e96-8936-8d9edef9510a">

`--color=` doesn't seem to be a valid flag in the version of Flamegraph I used, so maybe it used to be?

Either way, I'm proposing removing that line from the docs.

**Comment by danicheg** [comment]
Hey @acloudmovingby. I wasn't able to reproduce the issue. I followed these steps:
1. Cloned the `scalacenter/scalac-profiling` repository: `git clone git@github.com:scalacenter/scalac-profiling.git`
2. `cd` into the `external/Flamegraph` directory
3. Executed the `git submodule update --init` (an important part)
4. Run the command including `--color=scala-compilation`:
```
/flamegraph.pl \
    --hash --countname="μs" \
    --color=scala-compilation \
    /Users/.../implicit-searches-global.flamegraph > compile-all-modules.svg
```
I got my coloured graph painted as expected:
<img width="1202" alt="Screenshot 2024-03-27 at 08 42 26" src="https://github.com/scalacenter/scalac-profiling/assets/19841757/a967b0e9-1131-401b-bbce-9deced342158">
