### ISSUE TITLE
NPE when starting sbt console with scalac-profiling

### ISSUE THREAD

**Issue by anish749** [scalacenter/scalac-profiling#29]
I was trying out [this](https://www.scala-lang.org/blog/2018/06/04/scalac-profiling.html) guide to profile a project.

I added the following in sbt
```
  "-Ycache-plugin-class-loader:last-modified",
  "-Xplugin:$PATH_TO_PLUGIN_JAR",
  "-P:scalac-profiling:no-profiledb",
  "-P:scalac-profiling:show-profiles",
  "-P:scalac-profiling:sourceroot:$BLOOP_CODEBASE_DIRECTORY"
```

When I do `console` from sbt shell, I get a NPE [here](https://github.com/scalacenter/scalac-profiling/blob/master/plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala#L267)
  as `_.file` returns `null`

**Comment by mikla** [comment]
@anish749 have you replaced `PATH_TO_PLUGIN_JAR` and `BLOOP_CODEBASE_DIRECTORY` with correct values?
