### ISSUE TITLE
Release for Scala 2.13

### ISSUE THREAD

**Issue by neko-kai** [scalacenter/scalac-profiling#30]
Scala 2.13 is out! However it seems like this plugin only builds for 2.12 currently

**Comment by leonardehrenfried** [comment]
I took it upon me to provide a 2.13 version.

It is available here: https://gitlab.com/leonard.ehrenfried/scalac-profiling

It's a bit of a work in progress but the scalac plugin is working. I wanted to port the build to sbt 1 but failed at moving over the sbt plugin and the integration test suite. Perhaps one day I will do that too.

Feedback is welcome.

**Comment by SethTisue** [comment]
@sjrd (is there perhaps someone at the Scala Center who has an interest in this...?)

**Comment by jvican** [comment]
@leonardehrenfried Could you send a PR? I'm happy to review the PR :wink:

**Comment by leonardehrenfried** [comment]
The problem with my fork is that it's 2.13 only.

Also, I failed hard to understand the sbt 0.13 build and could not port it to 1.0. I also didn't want to downgrade to Java 8 so I could use sbt 0.13.

After having admitted defeat, I deleted the old build files and started a fresh sbt 1 build definition, which only compiles what I need: the scalac plugin for 2.13. What's missing are the integration tests and the sbt plugin.

The actual change to the plugin code is tiny (1 line).

So, I'm unsure how to proceed. I could just commit the change and pray that CI can build it. 

Or we communally take care of moving the complete build to 1.0.

**Comment by epifab** [comment]
it'd be great to have this resolved!

**Comment by SethTisue** [comment]
@sjrd ping one more time.... I won't bother you again

**Comment by sjrd** [comment]
Thanks for the reminder @SethTisue. We should somehow make sure to provide a 2.13 version, yes. We're basically at full capacity these months for the release of Scala 3, so I don't think we'll be able to dedicate someone to this very soon, though. If someone submits a PR, I'll make sure to review and merge it.

I think the first step will be to look at what happened to the CI, and probably migrate it to GitHub Actions or something else that's hosted.

**Comment by SethTisue** [comment]
PR: #32

**Comment by SethTisue** [comment]
@danicheg I can reshare any publicity, if you point me to it

**Comment by SethTisue** [comment]
> Ask some people from the community to try out the scalac-profiling in their projects. Not sure how loud this request should be

feel free to announce it on #links on Discord, and if you put it on Mastodon or Twitter or Bluesky or whatever I will reshare

> plus, add some tweaks to the original article

maybe just put a header at the top with a link to something that can be more easily kept up to date, e.g. the repo readme

**Comment by SethTisue** [comment]
@danicheg I re-shared your Mastodon post, and I also tweeted https://twitter.com/SethTisue/status/1717244376399991116 and bluesky'ed https://bsky.app/profile/sethtisue.bsky.social/post/3kclu3snymc2r

**Comment by danicheg** [comment]
@SethTisue that's ... huge 😄 Hopefully, this will help someone.

**Comment by SethTisue** [comment]
thank you so much for your effort and your patience on this.
