### ISSUE TITLE
Update FlameGraph

### ISSUE THREAD

**Issue by danicheg** [scalacenter/scalac-profiling#38]
I'd like to update FlameGraph. I've applied several patches to the latest FlameGraph, just like Jorge made 5 years ago on his fork, and all appears to be good. If you can fork the [FlameGraph](https://github.com/brendangregg/FlameGraph) into the Scala Center Github organization, I will do the rest of the stuff. @sjrd wdyt?

**Comment by lolgab** [comment]
Is it necessary to maintain a fork of FlameGraph in a submodule? Is it possible to generate data in a way that the official FlameGraph can render it?

**Comment by danicheg** [comment]
Yes, we have to maintain our current fork, because we need to plug into it support of `scalac-profiling`. Otherwise, we need to rewrite the `scalac-profiling` in a way that will fake the output to support the default FlameGraph with its profiles (not the best choice, IMHO).
