### ISSUE TITLE
Display file name of offending implicits in flamegraph

### ISSUE THREAD

**Issue by lolgab** [scalacenter/scalac-profiling#44]
Looking at the flamegraph, it's hard to understand where the code is coming from. You need to guess.
It would be nice to have something that points to the definition of the function taking implicit parameters, so I can then check its usages or ways to improve it.

**Comment by danicheg** [comment]
We need someone from the scalac maintainers to confirm it's possible according to the gathering statistics approach (`-Ystatistics` compiler flag, I mean).
