### ISSUE TITLE
Flamegraphs are empty without the `-Ystatistics` option

### ISSUE THREAD

**Issue by lolgab** [scalacenter/scalac-profiling#45]
The compiler plugin doesn't generate useful data if you don't add the `-Ystatistics`.
It should fail the compilation or, at least, print a warning to inform the user to add the option.

**Comment by danicheg** [comment]
> The compiler plugin doesn't generate useful data if you don't add the -Ystatistics.

What does it look like for the end user? Is it an empty `.flamegraph` file?

**Comment by lolgab** [comment]
Most of them are empty, some of them have some data but all fail when you try to open them with `flamegraph`.
