### ISSUE TITLE
Move documentation to a more permanent home

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scalac-profiling#53]
It's not good for [a 2018 blog post](https://www.scala-lang.org/blog/2018/06/04/scalac-profiling.html) to also serve as the documentation. We should keep it in-repo so we can update it.

We could add a note to the top of the old post, redirecting readers to the current documentation. (This is what we did, for example, with https://www.lightbend.com/blog/scala-inliner-optimizer which eventually turned into the more permanent https://docs.scala-lang.org/overviews/compiler-options/optimizer.html.)

**Comment by danicheg** [comment]
The core docs have already been moved to https://scalacenter.github.io/scalac-profiling/. The rest will be there gradually.

**Comment by SethTisue** [comment]
> The rest will be there gradually

Is it too soon to add the notice to the blog post, then? Or should I go ahead?

**Comment by danicheg** [comment]
> Or should I go ahead?

I think the microsite is good enough already. And so, go ahead.

**Comment by SethTisue** [comment]
PR https://github.com/scala/scala-lang/pull/1590
