### ISSUE TITLE
Depends on the Flamegraph git project based in the Center organization

### ISSUE THREAD

**Issue by danicheg** [scalacenter/scalac-profiling#71]
At the moment, `scalac-profiling` depends on the [fork of Flamegraph](https://github.com/jvican/FlameGraph/ ), which is seemingly abandoned and hasn't been updated for 5+ years. It'd be beneficial if someone could create a fresh fork based in the Center organization. Who can assist with that? cc @SethTisue @sjrd

**Comment by danicheg** [comment]
> curious what the nature of the changes is... is it anything that could be upstreamed?

1. Update the Flamegraph library we depend on.
2. Generally be able to develop/update our fork on demand. It's barely that Jorge is interested in it.
3. Cut down the abandoned dependencies.

**Comment by danicheg** [comment]
@SethTisue any thoughts on this?

**Comment by SethTisue** [comment]
> curious what the nature of the changes is

what I meant by this was, what is the nature of the changes that Jorge made in the fork? perhaps Jorge's changes could be submitted to https://github.com/brendangregg/FlameGraph and if they were merged, then having a fork would no longer be necessary

> It'd be beneficial if someone could create a fresh fork based in the Center organization

seems reasonable to me (even as a temporary measure if we also pursue the upstreaming idea), but I don't have admin rights in scalacenter/*, so @sjrd would have to take care of it

**Comment by danicheg** [comment]
@sjrd would you mind taking a look at this issue?

**Comment by danicheg** [comment]
@sjrd Be well soon! I'm wondering about doing these two particular things:
1. Fork the https://github.com/brendangregg/FlameGraph into Center Github org;
2. Create a branch `scala-compilation` based on the `master` branch and push it into the origin.

I will do the rest of the stuff. It'd be great if you folks @adpi2 @anatoliykmetyuk could do that. Thank you!

**Comment by danicheg** [comment]
Cool, thanks again.

**Comment by danicheg** [comment]
Done in #84
