### ISSUE TITLE
Embedded SVGs on the website are not clickable

### ISSUE THREAD

**Issue by danicheg** [scalacenter/scalac-profiling#79]
That's strange because when building the website locally, everything is fine, and SVGs are clickable as expected 🤔 
```
scala-steward-implicit-searches-flamegraph.svg:125 Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
    at g_to_text (scala-steward-implicit-searches-flamegraph.svg:125:36)
    at scala-steward-implicit-searches-flamegraph.svg:59:50
scala-steward-implicit-searches-flamegraph.svg:65 Uncaught TypeError: Cannot set properties of undefined (setting 'nodeValue')
    at scala-steward-implicit-searches-flamegraph.svg:65:33
```

**Comment by danicheg** [comment]
I figured out that when the site is being published the FlameGraph SVG image is copied to the `gh-pages` branch, and it changes from the original one (compresses and results in missing XML structure). I manually replaced the image in `gh-pages` from `main`. But I'm unsure whether it will be replaced once again when the site is published.

**Comment by danicheg** [comment]
And yes, it was overridden once again 😞 https://github.com/scalacenter/scalac-profiling/actions/runs/7457211480
As a temporary fix, we can manually change the image after every publishing. But doubtless, this is clunky.

**Comment by danicheg** [comment]
A while ago opened an issue in the `mdoc` project https://github.com/scalameta/mdoc/issues/833. 
Currently, the only workaround is to manually replace images in the `gh-pages` branch.

**Comment by danicheg** [comment]
Aaaand, it's fixed.

**Comment by SethTisue** [comment]
🎉
